skycli user signup
SkygearIO/skycli pull request #91
Opened 2019-03-18 07:00 UTC by carmenlau

connect #89 

WIP: command validation, e.g. user call signup before setting up cluster.

2019-03-19 10:41 UTC, kaojohnny requested changes

2019-03-19 10:41 UTC, kaojohnny commented on src/types/user.ts
> +        meta: metaFromJSON(input.profile),
should be `input.metadata`.

2019-03-19 11:19 UTC, carmenlau commented
Updated, thanks @kaojohnny

2019-03-20 02:16 UTC, kaojohnny approved these changes

2019-03-20 02:16 UTC, merged